# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import algotourrouter_pb2 as algotourrouter__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in algotourrouter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlgorouterStub(object):
    """The Algorouter service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoRouting = channel.unary_unary(
                '/algotourrouter.Algorouter/DoRouting',
                request_serializer=algotourrouter__pb2.RouteRequestRPC.SerializeToString,
                response_deserializer=algotourrouter__pb2.RouteResponse.FromString,
                _registered_method=True)


class AlgorouterServicer(object):
    """The Algorouter service definition.
    """

    def DoRouting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoRouting': grpc.unary_unary_rpc_method_handler(
                    servicer.DoRouting,
                    request_deserializer=algotourrouter__pb2.RouteRequestRPC.FromString,
                    response_serializer=algotourrouter__pb2.RouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algotourrouter.Algorouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algotourrouter.Algorouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Algorouter(object):
    """The Algorouter service definition.
    """

    @staticmethod
    def DoRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algotourrouter.Algorouter/DoRouting',
            algotourrouter__pb2.RouteRequestRPC.SerializeToString,
            algotourrouter__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
